name: Terraform Deploy

on:
    push:
        branches:
            - main

env:
    AWS_REGION: us-east-1
    TF_VERSION: "1.12.1"
    PROJECT_NAME: terraform-ansible-ssm

jobs:
    deploy:
        name: Deploy Infrastructure and Configure Servers
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: ./

        permissions:
            id-token: write # Required for OIDC authentication
            contents: read # Required to checkout the repository

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: ${{ env.TF_VERSION }}

            - name: Terraform Init
              id: init
              run: terraform init -input=false

            - name: Terraform Format Check
              id: fmt
              run: terraform fmt -check -recursive

            - name: Terraform Validate
              id: validate
              run: terraform validate

            - name: Terraform Plan
              id: plan
              run: terraform plan 
              continue-on-error: true

            - name: Terraform Plan Status
              if: steps.plan.outcome == 'failure'
              run: exit 1

            - name: Terraform Apply
              id: apply
              run: terraform destroy  -auto-approve

            - name: Deployment status notification
              if: always()
              run: |
                  if [ "${{ job.status }}" = "success" ]; then
                    echo "✅ Deployment completed successfully!"
                  else
                    echo "❌ Deployment failed!"
                    exit 1
                  fi
